config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :articles

  root "feeds#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :feed
  
  scope :desc_by_date,   -> { order("articles.date DESC") }
end

app/models/feed.rb
require 'open-uri'
require "net/http"
require 'rss'

class Feed < ApplicationRecord
  validates_uniqueness_of :url

  has_many :articles, dependent: :destroy

  before_validation :sanitize_strings
  before_save :set_articles

  private

  def sanitize_strings
    attributes.each { |_, value| value.try(:strip!) }
  end

  def set_articles
    if articles.empty? 
       articles << parse_articles
    end 
  end 
  
  def parse_articles
    data = open(url)
    feed = RSS::Parser.parse(data, false)
    self[:name] = feed.channel.title
    self[:link] = feed.channel.link 
    feed.channel.items.collect do | item |
        parse_description = Nokogiri::HTML(item.description).css("body").text
        item_date = item.date
        item_date = DateTime.now if item_date.nil?
        new_article = Article.create(title: item.title, description: parse_description ,  link: item.link, date: item_date.strftime("%B %d, %Y") )
        new_article
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.desc_by_date
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :link, :date, :feed_id)
    end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feed_params
      params.require(:feed).permit(:url, :name, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style='text-align: center;'>Articles (<%= @articles.count %>)</h1>
<% if @articles.length > 0 %>
  <% @articles.each do |article| %>
    <p><%= link_to article.title, article %></p>
  <% end %>
<% else %>
  <h2> No articles found... </h2>
<% end %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="gallery">
  <h2><%= @article.title %> : <%= @article.date.strftime("%B %d, %Y") %> </h2>
  <a target="_blank" href="<%= @article.link %>"><%= @article.link %></a>
  <div class="desc"><%= @article.description %></div>
</div>

<br>
<br>

<%= link_to 'Back', articles_path %>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @feed.persisted? %>
    <p>
      <strong>Url:</strong>
      <%= @feed.url %>
    </p>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :feed_name %>
    </div>

    <div class="field">
      <%= form.label :link %>
      <%= form.text_field :link, id: :feed_link %>
    </div>
  <% else %>
    <div class="field">
      <%= form.label :url %>
      <%= form.text_field :url, id: :feed_url %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style='text-align: center;'>Feeds (<%= @feeds.count %>)</h1>

<%= link_to 'New Feed', new_feed_path %>

<br>
<br>
<% if @feeds.length > 0 %>
  <table id='feeds-table'>
    <thead>
      <tr>
        <th>Url</th>
        <th>Name</th>
        <th>Link</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @feeds.each do |feed| %>
        <tr>
          <td><a href="<%= feed.url %>"><%= feed.url %></a></td>
          <td><%= feed.name %></td>
          <td><a href="<%= feed.link %>"><%= feed.link %></a></td>
          <td><%= link_to 'Show', feed %></td>
          <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
          <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2> No feeds found... </h2>
<% end %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Link:</strong>
  <%= @feed.link %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RssReader</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <a href="#default" class="logo">RSS reader</a>
      <div class="header-right">
        <a class="<%= (request.env['PATH_INFO'].include? 'feeds') ? 'active' : '' %>" href="<%= feeds_path %>">Feeds</a>
        <a class="<%= (request.env['PATH_INFO'].include? 'articles') ? 'active' : '' %>" href="<%= articles_path %>">Articles</a>
      </div>
    </div>
    <div style="padding-left:20px">
      <%= yield %>
    </div>
  </body>
</html>